_wandb:
    value:
        cli_version: 0.21.0
        e:
            di20p9qospkt7douwyfuh6u8pkbwczdz:
                args:
                    - --model_dir=./mol_dqn/save
                    - --hparams=./mol_dqn/chemgraph/configs/naive_dqn.json
                    - --wandb_project=mol-dqn-qed-optimization
                    - --wandb_run_name=naive_dqn_run_1
                    - --use_wandb
                    - "true"
                codePath: mol_dqn/chemgraph/optimize_qed.py
                codePathLocal: mol_dqn/chemgraph/optimize_qed.py
                email: yongkunyang11@gmail.com
                executable: /data/yyk/miniconda3/envs/moldqn/bin/python
                git:
                    commit: 51cf8677ac820dcf12b3adfa9b85f76ed3da2069
                    remote: https://github.com/Absurd2004/MolDQN-pytorch.git
                host: zkti
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /data/yyk/mol_dqn_pytorch/./mol_dqn/chemgraph/optimize_qed.py
                python: CPython 3.10.0
                root: /data/yyk/mol_dqn_pytorch
                startedAt: "2025-07-22T16:16:42.423568Z"
                writerId: di20p9qospkt7douwyfuh6u8pkbwczdz
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.0
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
hparams:
    value: ./mol_dqn/chemgraph/configs/naive_dqn.json
model_dir:
    value: ./mol_dqn/save
start_molecule:
    value: null
use_wandb:
    value: true
wandb_project:
    value: mol-dqn-qed-optimization
wandb_run_name:
    value: naive_dqn_run_1
