_wandb:
    value:
        cli_version: 0.21.0
        e:
            10k55z8kzemy17xx3wt66lnfi6k9hjxn:
                args:
                    - --model_dir=./mol_dqn/save
                    - --hparams=./mol_dqn/chemgraph/configs/naive_dqn.json
                    - --wandb_project=mol-dqn-qed-optimization
                    - --wandb_run_name=naive_dqn_run_1
                    - --use_wandb
                    - "true"
                codePath: mol_dqn/chemgraph/optimize_qed.py
                codePathLocal: mol_dqn/chemgraph/optimize_qed.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "878357635072"
                        used: "31847530496"
                email: yongkunyang11@gmail.com
                executable: /data/yyk/miniconda3/envs/moldqn/bin/python
                git:
                    commit: 51cf8677ac820dcf12b3adfa9b85f76ed3da2069
                    remote: https://github.com/Absurd2004/MolDQN-pytorch.git
                gpu: NVIDIA L40
                gpu_count: 6
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-ad526566-2257-46ab-de49-40f4d28bf516
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-1d6ddd9a-027e-4491-5eb3-7b5e41187453
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-2086e9ab-bceb-04de-ff9f-ba878a355bea
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-6f9d79d1-76e3-2c67-a12d-4839762098a2
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-e94ab396-e1b9-d826-cf39-c40b2e86632c
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-9c2c64b2-5966-66e1-1a5e-debac45d5ef9
                host: zkti
                memory:
                    total: "270080507904"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /data/yyk/mol_dqn_pytorch/./mol_dqn/chemgraph/optimize_qed.py
                python: CPython 3.10.0
                root: /data/yyk/mol_dqn_pytorch
                startedAt: "2025-07-22T16:19:12.697098Z"
                writerId: 10k55z8kzemy17xx3wt66lnfi6k9hjxn
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.0
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
activation:
    value: relu
allow_bonds_between_rings:
    value: false
allow_no_modification:
    value: true
allow_removal:
    value: true
allowed_ring_sizes:
    value:
        - 5
        - 6
atom_types:
    value:
        - C
        - O
        - "N"
batch_norm:
    value: false
batch_size:
    value: 128
dense_layers:
    value:
        - 1024
        - 512
        - 128
        - 32
discount_factor:
    value: 0.9
double_q:
    value: true
fingerprint_length:
    value: 2048
fingerprint_radius:
    value: 3
gamma:
    value: 1
grad_clipping:
    value: 10
hparams:
    value: ./mol_dqn/chemgraph/configs/naive_dqn.json
learning_frequency:
    value: 4
learning_rate:
    value: 0.0001
learning_rate_decay_rate:
    value: 0.9
learning_rate_decay_steps:
    value: 10000
max_num_checkpoints:
    value: 10
max_steps_per_episode:
    value: 40
model_dir:
    value: ./mol_dqn/save
num_bootstrap_heads:
    value: 0
num_episodes:
    value: 5000
optimizer:
    value: Adam
prioritized:
    value: false
prioritized_alpha:
    value: 0.6
prioritized_beta:
    value: 0.4
prioritized_epsilon:
    value: 1e-06
replay_buffer_size:
    value: 5000
save_frequency:
    value: 200
start_molecule:
    value: null
update_frequency:
    value: 20
use_wandb:
    value: true
wandb_project:
    value: mol-dqn-qed-optimization
wandb_run_name:
    value: naive_dqn_run_1
